include ../vars.mk

PROGRAMS = args-probe
LIBRARIES = libargs-advise.so

DIST_PROGRAMS = $(PROGRAMS)
DIST_LIBRARIES = $(LIBRARIES)

args-probe_SRCS = args-probe.c
libargs-advise.so_SRCS = args-advise.c

include $(TOPDIR)/rules.mk
