include ../vars.mk

dist_bin = args-probe
dist_lib = libargs-advise.so

args-probe_SRCS = args-probe.c

libargs-advise.so_SRCS = args-advise.c
libargs-advise.so_CFLAGS = -fPIC

include $(TOPDIR)/rules.mk
